[package]
name = "async-embedded-sdmmc"
description = "Embedded sdmmc driver with async support"
license = "MIT OR Apache-2.0"
version = "0.1.3"
authors = ["qiuchengxuan <qiuchengxuan@gmail.com>"]
edition = "2021"
repository = "https://github.com/qiuchengxuan/async-sdmmc"

[dependencies]
async-trait = "0.1"
bitfield = "0.13"
deasync = "0.1"
embedded-hal = "0.2"
fugit = { version = "0.3", optional = true }
gpio = { version = "0.4", optional = true }
log = "0.4"
nb = "1.0"
spidev = { version = "0.5", optional = true }
void = { version = "1.0", optional = true }

[dev-dependencies]
hex-literal = "0.3"

[features]
async = []
std = []
linux-spi = ["std", "gpio", "void", "spidev"]
log-max-level-off = ["log/max_level_off", "log/release_max_level_off"]

[lib]
name = "sdmmc"
